### ISSUE TITLE
Segfault if fiddling with "equalize" box while it's generating a composite

### ISSUE THREAD

**Issue by RAD750** [altillimity/SatDump#215]
**Description of the issue**
Fiddling with the Equalize checkbox in the product viewer (either checking it or unchecking it) causes a segfault.
I tried both with Metop data and Meteor data, although the crash seems to be slightly different (!)

Steps to reproduce (Meteor):
1. Load up Meteor dataset from viewer (sample below)
2. Extend Image Tab so you can fiddle with the box
3. Go to RGB composites
4. Select Natural Color
5. While it's generating tick the equalize box (sometimes a one time is sufficient, other times it needs to be done several time)

Steps to reproduce (Metop):
1. Load up Meteor dataset from viewer (sample below)
2. Extend Image Tab so you can fiddle with the box
3. Go to RGB composites
4. Select NIR (but it's the same with other compos)
5. While it's generating tick the equalize box (sometimes a one time is sufficient, other times it needs to be done several time)

**Hardware (SDR/PC/OS)**
Thinkpad X260, Pop!_OS 22.04

**Version**
1.0.3 - cddbbfc9 
compiled yesterday evening (Aang knows why :rofl:)

**Logs after the crash (satdump.logs)**
[satdump.log](https://github.com/altillimity/SatDump/files/10207305/satdump.log) (nothing useful in it)

I ran it through gdb:

Crash with Meteor data:
```
Thread 3 "satdump-ui" received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff5fe6640 (LWP 192839)]
__pthread_kill_implementation (no_tid=0, signo=6, threadid=140737320478272) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: File o directory non esistente.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140737320478272)
    at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=140737320478272)
    at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=140737320478272, signo=signo@entry=6)
    at ./nptl/pthread_kill.c:89
#3  0x00007ffff6c42476 in __GI_raise (sig=sig@entry=6)
    at ../sysdeps/posix/raise.c:26
#4  0x00007ffff6c287f3 in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff6c896f6 in __libc_message (action=action@entry=do_abort, 
    fmt=fmt@entry=0x7ffff6ddbb8c "%s\n") at ../sysdeps/posix/libc_fatal.c:155
#6  0x00007ffff6ca0d7c in malloc_printerr (
    str=str@entry=0x7ffff6dd977c "free(): invalid size")
    at ./malloc/malloc.c:5664
#7  0x00007ffff6ca2ad4 in _int_free (av=<optimized out>, p=0x7fff69ff3000, 
    have_lock=0) at ./malloc/malloc.c:4443
#8  0x00007ffff6ca54d3 in __GI___libc_free (mem=<optimized out>)
    at ./malloc/malloc.c:3391
#9  0x00007ffff799678c in image::Image<unsigned short>::init(unsigned long, unsigned long, int) () from /lib/libsatdump_core.so
#10 0x00007ffff7996841 in image::Image<unsigned short>::operator=(image::Image<unsigned short> const&) () from /lib/libsatdump_core.so
#11 0x00005555555f846b in satdump::ImageViewerHandler::updateImage() ()
--Type <RET> for more, q to quit, c to continue without paging--c
#12 0x00005555555f9916 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<satdump::ImageViewerHandler::asyncUpdate()::{lambda(int)#1}, std::allocator<int>, void (int)>::_M_run(int&&)::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) ()
#13 0x000055555558ec0d in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) ()
#14 0x00007ffff6c99f68 in __pthread_once_slow (once_control=0x555556f887f8, init_routine=0x7ffff70dadb0 <__once_proxy>) at ./nptl/pthread_once.c:116
#15 0x00005555555f3b27 in std::__future_base::_Task_state<satdump::ImageViewerHandler::asyncUpdate()::{lambda(int)#1}, std::allocator<int>, void (int)>::_M_run(int&&) ()
#16 0x00005555555f3795 in std::_Function_handler<void (int), ctpl::thread_pool::push<satdump::ImageViewerHandler::asyncUpdate()::{lambda(int)#1}>(satdump::ImageViewerHandler::asyncUpdate()::{lambda(int)#1}&&)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
#17 0x00005555555a0b1b in ctpl::thread_pool::set_thread(int)::{lambda()#1}::operator()() const ()
#18 0x00007ffff70dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#19 0x00007ffff6c94b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#20 0x00007ffff6d26a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 
```

Crash with Metop data

```
Thread 2 "satdump-ui" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff67e7640 (LWP 194749)]
0x00007ffff79a0290 in image::Image<unsigned short>::equalize() () from /lib/libsatdump_core.so
(gdb) bt
#0  0x00007ffff79a0290 in image::Image<unsigned short>::equalize() ()
   from /lib/libsatdump_core.so
#1  0x00005555555f84b8 in satdump::ImageViewerHandler::updateImage() ()
#2  0x00005555555f9583 in satdump::ImageViewerHandler::updateRGB()::{lambda(int)#1}::operator()(int) const [clone .constprop.0] ()
#3  0x00005555555f97a0 in std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<void>, std::__future_base::_Result_base::_Deleter>, std::__future_base::_Task_state<satdump::ImageViewerHandler::updateRGB()::{lambda(int)#1}, std::allocator<int>, void (int)>::_M_run(int&&)::{lambda()#1}, void> >::_M_invoke(std::_Any_data const&) ()
#4  0x000055555558ec0d in std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*) ()
#5  0x00007ffff6c99f68 in __pthread_once_slow (once_control=0x55555716f2e8, 
    init_routine=0x7ffff70dadb0 <__once_proxy>) at ./nptl/pthread_once.c:116
#6  0x00005555555f3e77 in std::__future_base::_Task_state<satdump::ImageViewerHandler::updateRGB()::{lambda(int)#1}, std::allocator<int>, void (int)>::_M_run(int&&) ()
#7  0x00005555555f3365 in std::_Function_handler<void (int), ctpl::thread_pool::push<satdump::ImageViewerHandler::updateRGB()::{lambda(int)#1}>(satdump::ImageViewerHandler::updateRGB()::{lambda(int)#1}&&)::{lambda(int)#1}>::_M_invoke(std::_Any_data const&, int&&) ()
--Type <RET> for more, q to quit, c to continue without paging--c
#8  0x00005555555a0b1b in ctpl::thread_pool::set_thread(int)::{lambda()#1}::operator()() const ()
#9  0x00007ffff70dc2b3 in ?? () from /lib/x86_64-linux-gnu/libstdc++.so.6
#10 0x00007ffff6c94b43 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
#11 0x00007ffff6d26a00 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
(gdb) 
```

## Samples

Here: [https://proxima.a-centauri.com/stuff/metop-meteor-segfault/](https://proxima.a-centauri.com/stuff/metop-meteor-segfault/)

Special apologies to Aang for finding yet another horrible bug :joy:

**Comment by Aang23** [comment]
Ok this one actually isn't horrible at all. More an oversight. Easy enough to fix.
