### ISSUE TITLE
std::bad_function_call thrown when processing NOAA DSB to products

### ISSUE THREAD

**Issue by shuyuan-liu** [altillimity/SatDump#5]
## Description

When using the command-line version, the demodulation seems to work fine but as soon as SatDump starts "processing data to level products", the exception `std::bad_function_call` is thrown and the program crashes. Backtrace below:

```
#0  0x00007ffff727cef5 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff7266862 in abort () from /usr/lib/libc.so.6
#2  0x00007ffff74bd86a in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff74c9d3a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007ffff74c9da7 in std::terminate () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#5  0x00007ffff74ca04e in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=tinfo@entry=0x7ffff75f73b0 <typeinfo for std::bad_function_call>, 
    dest=dest@entry=0x7ffff74f44c0 <std::bad_function_call::~bad_function_call()>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#6  0x00007ffff74c07ac in std::__throw_bad_function_call () at /build/gcc/src/gcc/libstdc++-v3/src/c++11/functional.cc:34
#7  0x00007ffff7d4443f in std::function<std::shared_ptr<ProcessingModule> (std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >)>::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >) const (this=0x5555556f14c0, __args=std::map with 2 elements = {...}, __args=std::map with 2 elements = {...}, __args=std::map with 2 elements = {...})
    at /usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/10.2.0/../../../../include/c++/10.2.0/bits/std_function.h:621
#8  0x00007ffff7d42ec8 in Pipeline::run (this=0x5555556f3e60, input_file="/mnt/Data/Recordings/Audio/gqrx_20210326_113615_137350000_w8.wav", output_directory=".", 
    parameters=std::map with 2 elements = {...}, input_level="baseband", ui=false, 
    uiCallList=std::shared_ptr<std::vector<std::shared_ptr<ProcessingModule>, std::allocator<std::shared_ptr<ProcessingModule> > >> (empty) = {...}, 
    uiCallListMutex=std::shared_ptr<std::mutex> (empty) = {...}) at /home/shuyuan/Build/SatDump/src-core/pipeline.cpp:52
#9  0x000055555561b889 in main (argc=10, argv=0x7fffffffe1d8) at /home/shuyuan/Build/SatDump/src-cli/main.cpp:84
```

When using the GUI version, a blank screen is shown after demodulation finishes and nothing happens.

## Build info

- gcc 10.2.0
- libdsp built from source, commit 783dc00
- libcorrect built from source, commit f5a28c7
- volk 2.4
- fftw 3.3.9

## Sample source file

The following recording produced this error: https://drive.google.com/file/d/1o_NNQ6kTTxf93WYHNhh7QF4KC-t0yFd1/view?usp=sharing

**Comment by ZbychuButItWasTaken** [comment]
a HIRS decoder has been implemented in the last few commits and it will be available in the next release (very soon)
